export const SOCKET_GOOGLE_PULL_OUTOFOFFICECALENDAR_SUCCESS = 'SOCKET_GOOGLE_PULL_OUTOFOFFICECALENDAR_SUCCESS'
export const SOCKET_GOOGLE_PULL_CALENDAR_SUCCESS = 'SOCKET_GOOGLE_PULL_CALENDAR_SUCCESS'

// export const publishPlaylist = () => ({
//   type: PUBLISH_PLAYLIST,
//   overideQueue,
// })