export const REQUEST_HARVEST = 'REQUEST_HARVEST'
export const INVALIDATE_HARVEST = 'INVALIDATE_HARVEST'

export const HARVEST_UNAUTHORIZED = 'HARVEST_UNAUTHORIZED'
export const SOCKET_HARVEST_PULL_GETUSERSANDTIMES_SUCCESS = 'SOCKET_HARVEST_PULL_GETUSERSANDTIMES_SUCCESS'
export const SOCKET_HARVEST_PULL_GETUSERSANDTIMES_FAILED = 'SOCKET_HARVEST_PULL_GETUSERSANDTIMES_FAILED'
// Server actions.
export const HARVEST_PULL_GETUSERSANDTIMES_SUCCESS = 'HARVEST_PULL_GETUSERSANDTIMES_SUCCESS'
export const HARVEST_PULL_GETUSERSANDTIMES_ERROR = 'HARVEST_PULL_GETUSERSANDTIMES_ERROR'
export const HARVEST_NEW_POSTS_ERROR = 'HARVEST_NEW_POSTS_ERROR'
export const RECEIVE_HARVEST_POSTS_ERROR = 'RECEIVE_HARVEST_POSTS_ERROR'
export const NEED_TO_AUTH_HARVEST = 'NEED_TO_AUTH_HARVEST'
export const UPDATE_HARVEST_SORTING = 'UPDATE_HARVEST_SORTING'


// export const invalidateSonosData = ({
//   type: INVALIDATE_HARVEST
// })

export const newHarvestUsersAndTimes = (users) => ({
  type: HARVEST_PULL_GETUSERSANDTIMES_SUCCESS,
  users,
})

export const newHarvestUsersAndTimesError = (err) => ({
  type: HARVEST_PULL_GETUSERSANDTIMES_ERROR,
  message: err,
})

export const harvestUnauthorized = () => ({
  type: HARVEST_UNAUTHORIZED,
})

export const sortBy = (timePeriod) => ({
  type: UPDATE_HARVEST_SORTING,
  payload: timePeriod,
})
